### ISSUE TITLE
ログの使われ方がおかしいです

### ISSUE THREAD

**Issue by Ryotaguchi0803** [kstdx/task#1]
下記のような書き方ではなくlogパッケージを使った方がいいかもしれません
log.Println("hoge")
l
```
func Log(body string, colorCode int) {
	fmt.Println("\u001b[" + strconv.Itoa(colorCode) + "m" + body + "\u001b[0m")
}

func Err(body string) {
	Log(body, 31)
	os.Exit(0)
}

func Ok(body string) {
	Log(body, 32)
}

func Info(body string) {
	Log(body, 34)
}
```

**Comment by kstdx** [comment]
issueありがとうございます。
`Log()`関数ではなく`log.Println()`関数を利用した方が良いということでしょうか？
詳細を教えていただけると助かります(*≧∀≦*)

**Comment by Ryotaguchi0803** [comment]
> `Log()`関数ではなく`log.Println()`関数を利用した方が良いということでしょうか？

fmtは主に標準出力と文字列に対する操作をします
対してlogはアプリケーションのログ（行われた操作や結果）などを保存します

標準ライブラリのlogのコードを見るといいかもしれません
https://pkg.go.dev/log#Fatalln

また下記コードですが終了コードが0が指定されています.正常時には0,異常時には1など細かく設定して行くと良いかもしれません

func Err(body string) {
	Log(body, 31)
	os.Exit(0)
}

**Comment by kstdx** [comment]
遅れてすみません、返信ありがとうございます。

> fmtは主に標準出力と文字列に対する操作をします
> 対してlogはアプリケーションのログ（行われた操作や結果）などを保存します
はい。ですがfmtでも十分に機能しているのでこのままでいいかなと思います。

> また下記コードですが終了コードが0が指定されています.正常時には0,異常時には1など細かく設定して行くと良いかもしれません
エラーコードについては存じていますが、自分の環境だと1にすると不要なメッセージが発生しちゃうので0にしています :)

**Comment by Ryotaguchi0803** [comment]
まずログについて詳しく勉強した方がいいと思います．実行時間も表示されてないので…


エラーコードではなく，終了コードです．
なぜ，異常終了なのに0なのですか？となります

また与太話ですが，readmeの本文ですが英語は大文字から始まります
ならないうちは日本語で記入するのがいいと思います

一度他のOSSなどをみたら参考になると思います

**Comment by kstdx** [comment]
流石に英語の記法くらいは知っています。
好みで小文字にしているので、それが不快に思うなら別に使わないでもらって結構です😀
また、コードについては普通に間違えました。すみません。
以上終了あたりは個人使いなので別に良いかなと思ってつくっています。

もう一度言いますがあくまで個人使いで最初作っているので、修正要件があればPull Requestをお願いします🙇
